spring:
  profiles:
    active: dev

  application:
    name: App SALONES
# JWT
jwt:
  secret:
    key: AH7VlcnfzKzL7E2IZNyMl+3PtnDhprsZJz2xwjMB+SFSumnSbko863lmqG8IjQwn
  time:
    expiration: 86400000